-- -----------------------------------------------------------------------
-- Auto generated theme file. Do not edit!
-- -----------------------------------------------------------------------
nuklear.set_style(2, 255, 0xffffffff)  -- set custom style
nuklear.set_style_prop(indexes.NK_COLOR_TEXT, 0xffffffff)
nuklear.set_style_prop(indexes.NK_COLOR_WINDOW, 0xff000000)
nuklear.set_style_prop(indexes.NK_COLOR_HEADER, 0x800c3d46)
nuklear.set_style_prop(indexes.NK_COLOR_BORDER, 0xffad9f8c)
nuklear.set_style_prop(indexes.NK_COLOR_BUTTON, 0xff253237)
nuklear.set_style_prop(indexes.NK_COLOR_BUTTON_HOVER, 0xff6d94a0)
nuklear.set_style_prop(indexes.NK_COLOR_BUTTON_ACTIVE, 0xff5c6b73)
nuklear.set_style_prop(indexes.NK_COLOR_TOGGLE, 0xff5c6b73)
nuklear.set_style_prop(indexes.NK_COLOR_TOGGLE_HOVER, 0xffd7d7b6)
nuklear.set_style_prop(indexes.NK_COLOR_TOGGLE_CURSOR, 0xffe0b689)
nuklear.set_style_prop(indexes.NK_COLOR_SELECT, 0x800c3d46)
nuklear.set_style_prop(indexes.NK_COLOR_SELECT_ACTIVE, 0xff2c3b43)
nuklear.set_style_prop(indexes.NK_COLOR_SLIDER, 0xff5c6b73)
nuklear.set_style_prop(indexes.NK_COLOR_SLIDER_CURSOR, 0xf5e0b689)
nuklear.set_style_prop(indexes.NK_COLOR_SLIDER_CURSOR_HOVER, 0xffe5bc8e)
nuklear.set_style_prop(indexes.NK_COLOR_SLIDER_CURSOR_ACTIVE, 0xffeac193)
nuklear.set_style_prop(indexes.NK_COLOR_PROPERTY, 0xff5c6b73)
nuklear.set_style_prop(indexes.NK_COLOR_EDIT, 0x800c3d46)
nuklear.set_style_prop(indexes.NK_COLOR_EDIT_CURSOR, 0xff141414)
nuklear.set_style_prop(indexes.NK_COLOR_COMBO, 0x800c3d46)
nuklear.set_style_prop(indexes.NK_COLOR_CHART, 0xff000000)
nuklear.set_style_prop(indexes.NK_COLOR_CHART_COLOR, 0xff000000)
nuklear.set_style_prop(indexes.NK_COLOR_CHART_COLOR_HIGHLIGHT, 0xff0000ff)
nuklear.set_style_prop(indexes.NK_COLOR_SCROLLBAR, 0xff000000)
nuklear.set_style_prop(indexes.NK_COLOR_SCROLLBAR_CURSOR, 0xff5f5440)
nuklear.set_style_prop(indexes.NK_COLOR_SCROLLBAR_CURSOR_HOVER, 0xff645a46)
nuklear.set_style_prop(indexes.NK_COLOR_SCROLLBAR_CURSOR_ACTIVE, 0xff695f4b)
nuklear.set_style_prop(indexes.NK_COLOR_TAB_HEADER, 0x800c3d46)
nuklear.set_style_table()
